In [ ]:
import numpy as np

## 1. You have a random matrix n by m, how to select the numbers with certain conditions, but outcome matrix should be the same size as original one, the unselected ones can be returned as 0

In [ ]:
c = np.random.normal(0, 1, size=(3, 4)) * 10; c
condition = ((c > -3) & (c < 3))
np.where(condition, c, 0)

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-2.21056267,  0.        ,  0.        ,  0.        ]])

## 2. how to concatenate two n by m matrices (arrays) and are you able compute its invese?

In [ ]:
a = np.random.normal(0, 1, size=(2, 4)) * 10
b = np.random.normal(0, 1, size=(2, 4)) * 10
np.linalg.inv(np.concatenate([a, b], axis=0))

array([[ 0.04648423,  0.07373445, -0.06100933, -0.02948205],
       [ 0.04949594,  0.07937969, -0.07083186,  0.02410747],
       [-0.18932428, -0.36620135,  0.17220079, -0.01369898],
       [ 0.03320353, -0.12779359,  0.03905339, -0.02265369]])

## 3. Convert a n by m matrix to a 1D array in three ways?

In [ ]:
a = np.random.normal(0, 1, size=(3, 4)) * 10; a

array([[ -3.28026218, -22.86017062,   8.96364327,  -7.50435972],
       [  0.75116655,  -4.21030226,  -9.25804057,  21.28141657],
       [ -2.62822788,  -0.66168747,  12.26301505, -11.56650951]])

In [ ]:
a.flatten(order='C')

array([ -3.28026218, -22.86017062,   8.96364327,  -7.50435972,
         0.75116655,  -4.21030226,  -9.25804057,  21.28141657,
        -2.62822788,  -0.66168747,  12.26301505, -11.56650951])

In [ ]:
np.ravel(a, order='F')

array([ -3.28026218,   0.75116655,  -2.62822788, -22.86017062,
        -4.21030226,  -0.66168747,   8.96364327,  -9.25804057,
        12.26301505,  -7.50435972,  21.28141657, -11.56650951])

In [ ]:
a.reshape(-1, order='C')

array([ -3.28026218, -22.86017062,   8.96364327,  -7.50435972,
         0.75116655,  -4.21030226,  -9.25804057,  21.28141657,
        -2.62822788,  -0.66168747,  12.26301505, -11.56650951])

## 4. How do you create a matrix scatter with NaN, and you can filter out the NaN. 

In [ ]:
a = np.random.randn(10) * 10; a

array([-1.70418812e+01,  8.19198883e-01,  2.03242027e+00, -1.94401136e+01,
        7.51762484e+00, -4.40378360e+00, -1.58076226e+01, -2.63969867e-02,
       -4.33588185e+00, -2.82669427e+01])

In [ ]:
nan_index = np.random.choice(len(a), 3, replace=False); nan_index

array([7, 9, 5])

In [ ]:
a[nan_index] = np.nan; a

array([-17.04188122,   0.81919888,   2.03242027, -19.44011356,
         7.51762484,          nan, -15.80762257,          nan,
        -4.33588185,          nan])

In [ ]:
a = a.reshape(5, 2)

In [ ]:
np.where(np.isnan(a), 0, a) # replace nan by 0

array([[-17.04188122,   0.81919888],
       [  2.03242027, -19.44011356],
       [  7.51762484,   0.        ],
       [-15.80762257,   0.        ],
       [ -4.33588185,   0.        ]])

## 5. If you have a array, you set a condition, how do you get indices of them?

In [ ]:
a = np.random.randn(100) * 100
a = a.astype(int); a

array([ -14,  161, -115,  215,  -61,    2,  -56,   11,   38, -112, -137,
         56,  -38,   82,   32,  259, -178,   50,  105,  -99,   37,  -17,
        -61,   67,  206,  119,  -13,  -50, -112,   89,  114, -158,   45,
        122,   29,  -10, -123,    7,   51,  -96,  152,  212,   65, -202,
        185,   11,  -63,   16,  152,   14,  -65,  174,   92,   48,  -51,
        132,  -45,   44,   10,   -8,   -3,  122, -128,  122,  -72,  -53,
        -96,  -82,   12,  156,  209,  -85, -190,  105,   48,  140, -100,
         29,    5,   52,  -39, -187,  -69,   73,  -47,   33,  -71, -176,
       -148,   72,  -72,   10, -157,   10,   -8,    7, -186,  -56,   70,
         98])

In [ ]:
condition = (a > 90)
np.where(condition)

(array([ 1,  3, 15, 18, 24, 25, 30, 33, 40, 41, 44, 48, 51, 52, 55, 61, 63,
        69, 70, 73, 75, 99], dtype=int64),)

## 6. Sort an array from max to min? 

In [ ]:
a = np.random.randn(100) * 100
a = a.astype(int)
np.sort(a)[::-1]

array([ 265,  230,  217,  211,  200,  173,  172,  167,  146,  143,  130,
        128,  124,  123,  120,  119,  114,  105,  102,  100,   99,   88,
         87,   83,   74,   71,   66,   62,   59,   57,   54,   54,   52,
         51,   50,   46,   44,   42,   39,   37,   35,   34,   33,   28,
         27,   26,   25,   18,   16,   15,   10,    5,    4,    3,    1,
          0,   -3,   -3,   -5,  -12,  -15,  -17,  -17,  -19,  -19,  -22,
        -23,  -24,  -25,  -29,  -29,  -33,  -33,  -36,  -40,  -43,  -47,
        -47,  -49,  -51,  -52,  -54,  -56,  -58,  -77,  -80,  -81,  -84,
        -87,  -92, -106, -115, -119, -120, -129, -154, -169, -169, -173,
       -203])

## 7. Create a diagonal matrix with elements from 1 to 6

In [ ]:
np.diag(np.arange(1, 6), k=0)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])